name: Deploy WordPress Site
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy files via rsyn
        run: |
          rsync -avz --delete ./wp-content/plugins/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/plugins-upload
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo cp -r /tmp/plugins-upload/* /var/www/html/WordPress/wp-content/plugins/'
